// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServiceDeskBot.Infrastructure.Persistence;

#nullable disable

namespace ServiceDeskBot.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260911184157_AdicionaFluentApiENavegacoes")]
    partial class AdicionaFluentApiENavegacoes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServiceDeskBot.Domain.Entidades.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("ServiceDeskBot.Domain.Entidades.Chamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataInicioAtendimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Diagnostico")
                        .HasColumnType("text");

                    b.Property<int?>("EquipamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Impacto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("LocalId")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroChamado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Solucao")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("SubCategoriaId")
                        .HasColumnType("integer");

                    b.Property<int?>("TecnicoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("EquipamentoId");

                    b.HasIndex("LocalId");

                    b.HasIndex("NumeroChamado")
                        .IsUnique();

                    b.HasIndex("SubCategoriaId");

                    b.HasIndex("TecnicoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Chamados", (string)null);
                });

            modelBuilder.Entity("ServiceDeskBot.Domain.Entidades.Equipamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Critico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("LocalId")
                        .HasColumnType("integer");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Patrimonio")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("SetorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LocalId");

                    b.HasIndex("SetorId");

                    b.ToTable("Equipamentos", (string)null);
                });

            modelBuilder.Entity("ServiceDeskBot.Domain.Entidades.HistoricoChamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlteradoPorId")
                        .HasColumnType("integer");

                    b.Property<string>("CampoAlterado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ChamadoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TecnicoId")
                        .HasColumnType("integer");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("text");

                    b.Property<string>("ValorNovo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChamadoId");

                    b.HasIndex("TecnicoId");

                    b.ToTable("HistoricosChamados", (string)null);
                });

            modelBuilder.Entity("ServiceDeskBot.Domain.Entidades.InteracaoChatBot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChamadoId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MensagemEnviada")
                        .HasColumnType("text");

                    b.Property<string>("MensagemRecebida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChamadoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("InteracoesChatBot", (string)null);
                });

            modelBuilder.Entity("ServiceDeskBot.Domain.Entidades.Local", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Locais", (string)null);
                });

            modelBuilder.Entity("ServiceDeskBot.Domain.Entidades.Setor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LocalId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("LocalId");

                    b.ToTable("Setores", (string)null);
                });

            modelBuilder.Entity("ServiceDeskBot.Domain.Entidades.SubCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("SubCategorias", (string)null);
                });

            modelBuilder.Entity("ServiceDeskBot.Domain.Entidades.Tecnico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Tecnicos", (string)null);
                });

            modelBuilder.Entity("ServiceDeskBot.Domain.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("Telefone")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("ServiceDeskBot.Domain.Entidades.Chamado", b =>
                {
                    b.HasOne("ServiceDeskBot.Domain.Entidades.Categoria", "Categoria")
                        .WithMany("Chamados")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServiceDeskBot.Domain.Entidades.Equipamento", "Equipamento")
                        .WithMany("Chamados")
                        .HasForeignKey("EquipamentoId");

                    b.HasOne("ServiceDeskBot.Domain.Entidades.Local", "Local")
                        .WithMany("Chamados")
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServiceDeskBot.Domain.Entidades.SubCategoria", "SubCategoria")
                        .WithMany("Chamados")
                        .HasForeignKey("SubCategoriaId");

                    b.HasOne("ServiceDeskBot.Domain.Entidades.Tecnico", "Tecnico")
                        .WithMany("Chamados")
                        .HasForeignKey("TecnicoId");

                    b.HasOne("ServiceDeskBot.Domain.Entidades.Usuario", "Usuario")
                        .WithMany("Chamados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Equipamento");

                    b.Navigation("Local");

                    b.Navigation("SubCategoria");

                    b.Navigation("Tecnico");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ServiceDeskBot.Domain.Entidades.Equipamento", b =>
                {
                    b.HasOne("ServiceDeskBot.Domain.Entidades.Local", "Local")
                        .WithMany("Equipamentos")
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceDeskBot.Domain.Entidades.Setor", "Setor")
                        .WithMany("Equipamentos")
                        .HasForeignKey("SetorId");

                    b.Navigation("Local");

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("ServiceDeskBot.Domain.Entidades.HistoricoChamado", b =>
                {
                    b.HasOne("ServiceDeskBot.Domain.Entidades.Chamado", null)
                        .WithMany("HistoricoChamados")
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceDeskBot.Domain.Entidades.Tecnico", null)
                        .WithMany("AlteracoesFeitas")
                        .HasForeignKey("TecnicoId");
                });

            modelBuilder.Entity("ServiceDeskBot.Domain.Entidades.InteracaoChatBot", b =>
                {
                    b.HasOne("ServiceDeskBot.Domain.Entidades.Chamado", "Chamado")
                        .WithMany("InteracoesChatBot")
                        .HasForeignKey("ChamadoId");

                    b.HasOne("ServiceDeskBot.Domain.Entidades.Usuario", "Usuario")
                        .WithMany("InteracoesChatBot")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chamado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ServiceDeskBot.Domain.Entidades.Setor", b =>
                {
                    b.HasOne("ServiceDeskBot.Domain.Entidades.Local", "Local")
                        .WithMany("Setores")
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Local");
                });

            modelBuilder.Entity("ServiceDeskBot.Domain.Entidades.SubCategoria", b =>
                {
                    b.HasOne("ServiceDeskBot.Domain.Entidades.Categoria", "Categoria")
                        .WithMany("SubCategorias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ServiceDeskBot.Domain.Entidades.Categoria", b =>
                {
                    b.Navigation("Chamados");

                    b.Navigation("SubCategorias");
                });

            modelBuilder.Entity("ServiceDeskBot.Domain.Entidades.Chamado", b =>
                {
                    b.Navigation("HistoricoChamados");

                    b.Navigation("InteracoesChatBot");
                });

            modelBuilder.Entity("ServiceDeskBot.Domain.Entidades.Equipamento", b =>
                {
                    b.Navigation("Chamados");
                });

            modelBuilder.Entity("ServiceDeskBot.Domain.Entidades.Local", b =>
                {
                    b.Navigation("Chamados");

                    b.Navigation("Equipamentos");

                    b.Navigation("Setores");
                });

            modelBuilder.Entity("ServiceDeskBot.Domain.Entidades.Setor", b =>
                {
                    b.Navigation("Equipamentos");
                });

            modelBuilder.Entity("ServiceDeskBot.Domain.Entidades.SubCategoria", b =>
                {
                    b.Navigation("Chamados");
                });

            modelBuilder.Entity("ServiceDeskBot.Domain.Entidades.Tecnico", b =>
                {
                    b.Navigation("AlteracoesFeitas");

                    b.Navigation("Chamados");
                });

            modelBuilder.Entity("ServiceDeskBot.Domain.Entidades.Usuario", b =>
                {
                    b.Navigation("Chamados");

                    b.Navigation("InteracoesChatBot");
                });
#pragma warning restore 612, 618
        }
    }
}
